### ISSUE TITLE
How to configure collection view / filters to see tags?

### ISSUE THREAD

**Issue by pgmaier** [canopas/strapi-plugin-tagsinput#13]
Hello,

I have tagsInput running well but I do not see an option to configure the overall collection view or filters to display the custom tag. 

Thank you!

**Comment by cp-sumi-k** [comment]
@pgmaier I am not getting this, can you share more details? What type of feature do you want? 
You can also share some screenshots of UI

**Comment by pgmaier** [comment]
@cp-sumi-k Sorry I already deleted the plugin. Feel free to close this issue.
