### ISSUE TITLE
Filter by tag name

### ISSUE THREAD

**Issue by julia-fix** [canopas/strapi-plugin-tagsinput#14]
Trying to get posts by tag name with this code:
```
filters: {
  tags: {
    name: {
      $eqi: decodedTag,
    },
  },
},
```
but it returns all records, tried $containsi also but no difference. I checked tags structure in records, it is like [{name: string}] or null.

**Comment by julia-fix** [comment]
Ok I got the solution, it seems like we have to deal with stringified value:

```
filters: {
  tags: {
    $containsi: '"' + decodedTag + '"',
  },
},
```

Would be nice to mention it in the docs.

**Comment by cp-sumi-k** [comment]
@julia-fix You are trying to `fetch posts`, which is not related to this plugin, This is only for getting suggestions from all the tag's names.
