### ISSUE TITLE
Suggestion 403 error

### ISSUE THREAD

**Issue by bkreczmer** [canopas/strapi-plugin-tagsinput#16]
I've done exactly what docs says and Strapi showin 403 error when trying to reach /api/tags. 

 - API and admin are in the same domain.
 - Collection with tags created. 

Any suggestions?
Thank you ;)

**Comment by cp-sumi-k** [comment]
@bkreczmer Are you able to run API individually? 
Can you share details logs by inspecting the application in the browser?

**Comment by bkreczmer** [comment]
Yeah. API works fine - Ive git the rights answer, nut when trying to się suggestion from plugin im Strapi logs I see API URL and 403 error. Nothing more :(.Im custom field settings I be tried to idę/api/tags/api/tags?fields[0]=name Of course collection tag is created with field name.23 wrz 2024 15:04 Sumita Canopas ***@***.***> napisał(a):
@bkreczmer Are you able to run API individually?
Can you share details logs by inspecting the application in the browser?

**Comment by bkreczmer** [comment]
HI, I've founded what causes 403. I was permisstion to tags collection for public user. But now I am faceing with news issue. When tryin to type anything in tag field I've got "Woops! Something went wrong. Please, try again." in strapi admin :(

**Comment by cp-sumi-k** [comment]
@bkreczmer, can you investigate whether a plugin or some other code causes the issue?

**Comment by bkreczmer** [comment]
In console I have such issue:

main.ed6b1f6a.js:863 TypeError: ce.filter is not a function

and 

content_script.js:1 Uncaught TypeError: Cannot read properties of null (reading 'ControlLooksLikePasswordCredentialField')

it looks like admin can not show suggestions list. 
During 403 error in api, an admin works fine.

**Comment by bkreczmer** [comment]
also the anwser of api/tags?populate=deep&fields[0]=name 


{
    "data": [
        {
            "id": 1,
            "attributes": {
                "name": "ukulele"
            }
        },
        {
            "id": 2,
            "attributes": {
                "name": "test"
            }
        }
    ],
    "meta": {
        "pagination": {
            "page": 1,
            "pageSize": 25,
            "pageCount": 1,
            "total": 2
        }
    }
}

**Comment by bkreczmer** [comment]
Without public permissions in console this issue:



{
    "message": "Request failed with status code 403",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 403\n    at On (xxxxxx/admin/input-component.e7f8d97c.chunk.js:93:1057)\n    at XMLHttpRequest._e (xxxxxx/admin/input-component.e7f8d97c.chunk.js:93:4284)\n    at it.request (xxxxxx/admin/input-component.e7f8d97c.chunk.js:95:3113)\n    at async ge (xxxxxx/admin/input-component.e7f8d97c.chunk.js:96:5662)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*"
        },
        "method": "get",
        "url": "/api/tags?populate=deep&fields[0]=name"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 403
}

**Comment by bkreczmer** [comment]
Oookk .. case closed ;) update your plugin to 1.0.6 fixed the issue ;)
