### ISSUE TITLE
Is there a version that supports strapi v5?

### ISSUE THREAD

**Issue by sieftt** [canopas/strapi-plugin-tagsinput#17]
The official website says it supports 4.4.0 and above, when will it support strapi v5?

**Comment by sieftt** [comment]
I use it in strapi v5, get the error:
node_modules/strapi-plugin-tagsinput/admin/src/components/Input/index.js:119:6: ERROR: The JSX syntax extension is not currently enabled

**Comment by cp-sumi-k** [comment]
@sieftt It is [not currently supporting V5](https://github.com/canopas/strapi-plugin-tagsinput/issues/9). We added it in backlog and start working on it soon

**Comment by anshul-fitsib** [comment]
@cp-sumi-k 

Can you please tell us the tentative dates for Strapi V5 support?

**Comment by cp-sumi-k** [comment]
@anshul-fitsib I haven't decided on the official date for this yet, but due to requirements, I aim to complete it by October 15th. Just so you know, this is a tentative goal and may be subject to change.
