### ISSUE TITLE
When can we expect Strapi 5 support?

### ISSUE THREAD

**Issue by anshul-fitsib** [canopas/strapi-plugin-tagsinput#18]
Can you confirm the target date for the plugin update to support Strapi 5?

**Comment by cp-sumi-k** [comment]
@anshul-fitsib I haven't decided on the official date for this yet, but due to requirements, I aim to complete it by October 15th. Just so you know, this is a tentative goal and may be subject to change.

**Comment by cp-sumi-k** [comment]
Closing as completed in #19
