### ISSUE TITLE
How to search tag from rest api

### ISSUE THREAD

**Issue by phpmaple** [canopas/strapi-plugin-tagsinput#2]

**Comment by cp-sumi-k** [comment]
@phpmaple For such feature, we need to add **autocomplete** functionality with dynamic data (which can come from rest API). 
It would be great if you could contribute by creating a Pull Request for the feature. Feel free to let me know if you have any questions or need guidance.

**Comment by cp-sumi-k** [comment]
@phpmaple Implemented such functionality in [1.0.4](https://github.com/canopas/strapi-plugin-tagsinput/releases/tag/1.0.4). See if it can help you.
