### ISSUE TITLE
compatibility issue with versions

### ISSUE THREAD

**Issue by sachithraSP** [canopas/strapi-plugin-tagsinput#3]
can you please make this compatible with latest strapi and node 20
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from strapi-plugin-tagsinput@1.0.1
npm ERR! node_modules/strapi-plugin-tagsinput
npm ERR!   strapi-plugin-tagsinput@"*" from the root project

**Comment by cp-sumi-k** [comment]
@sachithraSP Done.  Checkout [1.0.3](https://github.com/canopas/strapi-plugin-tagsinput/releases/tag/1.0.3)
