### ISSUE TITLE
Use tag to filter

### ISSUE THREAD

**Issue by GerjoGreenwaldMM** [canopas/strapi-plugin-tagsinput#7]
Hi,

Thanks for creating this plugin. i have added the field to a promotions collection and now i'm trying to filter for it with the REST api. So far no success. I was trying something like:

/api/promotions?filters[$and][0][filterCode][code][name][$eq]=initial

Is this even expected to work this way?

**Comment by cp-sumi-k** [comment]
@GerjoGreenwaldMM, Please first check the API response in the browser or postman. If your api response is something like the below, then it should work. 

```
[
      { name: "tag1" },
      { name: "tag2" }
]
```

**Comment by arcadiy-magomedov** [comment]
> @GerjoGreenwaldMM, Please first check the API response in the browser or postman. If your api response is something like the below, then it should work.
> 
> ```
> [
>       { name: "tag1" },
>       { name: "tag2" }
> ]
> ```

I am using Postgres.

Tried in postman. No idea how to filter by tag value. In postgres I see a jsonb array of objects `{name: tag-value}`. Not sure knex knows how to filter by jsonb.

**Comment by gwu929** [comment]
but the strapi API reponse's format is different, it is like below, i.e. "Name": "swiss" is nested in data[0].attributes.Name 
just wondering if you could enhance the plugin so that it works with strapi API response out of box.
{
    "data": [
        {
            "id": 1,
            "attributes": {
                "Name": "swiss"
            }
        },
        {
            "id": 2,
            "attributes": {
                "Name": "german"
            }
        }
    ],
    "meta": {
        "pagination": {
            "page": 1,
            "pageSize": 25,
            "pageCount": 1,
            "total": 2
        }
    }
}

**Comment by arcadiy-magomedov** [comment]
@cp-sumi-k somehow i doubt that that pr fixes the issue described here

**Comment by cp-sumi-k** [comment]
@magom001 @GerjoGreenwaldMM  Plugin should work with the strapi API response and the previous custom response. 
I'm not sure about Jsonb and Knex.

Can you better elaborate your issue?
